-- Drop and recreate Maps table

DROP TABLE IF EXISTS maps CASCADE;
CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  zoom SMALLINT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  last_edit TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
