-- Drop and recreate Editors table

DROP TABLE IF EXISTS editors CASCADE;
CREATE TABLE editors (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);
